network: sepolia

postgres_dsn: "postgres://postgres:postgres@127.0.0.1:5432/hotwallet?sslmode=disable"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  stream:
    key: "blocks:raw"
    max_len: 100000

rpc:
  eth:
    http_url: "https://eth-sepolia.g.alchemy.com/v2/EFV8jNyGVN9Hi28lvUAx-"
    ws_url: "wss://eth-sepolia.g.alchemy.com/v2/EFV8jNyGVN9Hi28lvUAx-"
    timeout: "15s"
  pol:
    http_url: ""
    ws_url: "wss://polygon-amoy.g.alchemy.com/v2/EFV8jNyGVN9Hi28lvUAx-"
    timeout: "15s"
  btc:
    http_url: "https://bitcoin-testnet.g.alchemy.com/v2/EFV8jNyGVN9Hi28lvUAx-"
    ws_url: ""
    timeout: "15s"
  tron:
    http_url: "https://tron-testnet.g.alchemy.com/v2/EFV8jNyGVN9Hi28lvUAx-"
    ws_url: ""
    timeout: "15s"

sync:
  start_block: 0
  batch_size: 20
  confirmations: 0

